### ISSUE TITLE
Closing realm instance

### ISSUE THREAD

**Issue by GokhanArik** [niqdev/dagger-realm-test#1]
Hi,

I was looking at your example and I didn't see anywhere you closing realm instance. Isn't it a good practice to close it?

**Comment by niqdev** [comment]
Hi,
you are right! I would add a method in [DatabaseRealm](https://github.com/niqdev/dagger-realm-test/blob/master/app/src/main/java/com/github/niqdev/repository/DatabaseRealm.java), but where do you think is the more reliable place to close it?

**Comment by GokhanArik** [comment]
They recommend closing it `onDestroy()` of every component that uses it. If it is a non-activity class, at the end of operation you can close it. You just have to be careful when you close in a non-activitiy class. Since objects are live objects, when you close your instance you won't be able to access children of your object.

**Comment by niqdev** [comment]
Honestly I don't like to inject directly in all my activities and fragments `Realm` only to close it, for me should be injected and called only from `Repository` to keep the layers separated and I'd like to invoke it in a single exit point. Unfortunately there isn't something like `Application#onDestroy`, that would be perfect! Do you have any suggest?

**Comment by GokhanArik** [comment]
I agree, I don't like to do it neither but looks like there is no choice. I think the reason they don't have a single place to open/close instances is that realms can only be used in the thread they are created and if you try to use the same instance in different threads you will run into a  problem. One of the developers answered a question on StackOverFlow and said something like "if you don't close them it is not the end of the world, but it is good to close them". In my code, I inject it to my BaseActivity and close it onDestroy of it. All of my activities extend BaseActivity. If I need to use it in another thread I just create an instance there, use it, and then close. I don't know if that's the best approach.

EDIT

They actually talk about it here, he recommends to make it the way I did: https://github.com/realm/realm-java/issues/774#issuecomment-71013560

**Comment by niqdev** [comment]
What do you think about [Runtime.addShutdownHook](https://docs.oracle.com/javase/8/docs/technotes/guides/lang/hook-design.html) that will capture `System.exit()`? I might have a look at something like this, that will be registered once in the `Application#onCreate`:

``` java
Runtime.getRuntime().addShutdownHook(new Thread() {
    public void run() { database.close(); }
});
```

**Comment by niqdev** [comment]
So, I gave up!
I even thought about intercepting methods with aspects but is too overwhelming than simply call `onDestroy`.
[This](https://github.com/niqdev/dagger-realm-test/commit/78c4447f98bdc0b220bdbe22d08fe6858d2b8f39) commit close the issue
